### ISSUE TITLE
Add license headers to source files.

### ISSUE THREAD

**Issue by qyearsley** [jcgregorio/httplib2#307]
Reason: The page https://www.chromium.org/developers/adding-3rd-party-libraries suggests adding license headers to all source files used as third-party libraries for Chromium or related projects.

Without license headers, [chromium/src/tools/checklicenses/checklicenses.py](https://code.google.com/p/chromium/codesearch#chromium/src/tools/checklicenses/checklicenses.py) outputs a warning (until an exception is added to the list in that file).

I'm filing this now because I'm adding httplib2 into the third_party directory for [catapult](https://github.com/catapult-project/catapult), since the Chrome Performance Dashboard code is being moved there, and it depends on httplib2. Related CL: https://codereview.chromium.org/1274543002/.

**Comment by jcgregorio** [comment]
httplib2 is already in a whitelist in checklicenses.py:

https://code.google.com/p/chromium/codesearch#chromium/src/tools/checklicenses/checklicenses.py&l=434

**Comment by qeny** [comment]
It's currently in a whitelist for tools/swarming_client/third_party/httplib2; now there's a CL to add a separate entry in the whitelist for third_party/catapult/third_party/httplib2.

That "adding-3rd-party-libraries" page suggests to ask the upstream project author to add licenses in addition to adding an entry to the whitelist, so I filed this issue.

IMO the license seems pretty clear in the code since it has a __license__, __copyright__ and __author__ in there. (Maybe ideally checklicenses.py should check for these as well? But now I think it checks for a comment has a magic string like "Copyright ... under MIT license" in [licensecheck.pl](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/devscripts/licensecheck.pl))

**Comment by petrcermak** [comment]
In order for Chromium to be pulled into various Linux source distributions there's a requirement that all of the third party files pass the Linux <tt>licensecheck</tt> utility. Currently there are several files in the httplib2 repository missing per-file licenses. From a current run of <tt>licensecheck</tt>, they are:

```
$ licensecheck -r . | grep "No copyright"
./setup.py: *No copyright* UNKNOWN
./python2/httplib2/test/test_no_socket.py: *No copyright* UNKNOWN
./python2/httplib2/test/functional/test_proxies.py: *No copyright* UNKNOWN
./python2/httplib2/test/miniserver.py: *No copyright* UNKNOWN
./python2/httplib2/test/brokensocket/socket.py: *No copyright* UNKNOWN
./python2/httplib2/test/smoke_test.py: *No copyright* UNKNOWN
./libhttplib2.tex: *No copyright* UNKNOWN
```

We'd like to ask that per-file licenses be added to these files to make it easier to integrate httplib2 not only into Chromium, but also Linux distributions in general. Thanks.
